# Processing Language

In [1]:
import numpy as np

texts = ["My dog gets along with cats", #crea una lista de strings, cada fila es una oración
         "That cat is vicious",
         "My dog is happy when it is lunch"]

In [2]:
unique_words = set(word.lower() for phrase in texts for #al usar "set" obtiene las palabras únicas de 
                   word in phrase.split(" ")) #todo el texto y las guarda en la variable de unique_words
print(f"There are {len(unique_words)} unique words") #imprime la longitud de unique_words
        #que corresponde con el número de palabras únicas

There are 14 unique words


In [3]:
from keras.preprocessing.text import Tokenizer #libreria para convertir en tokens las palabras
vocabulary_size = len(unique_words) + 1 # Obtiene el número de palabras únicas y le agrega 1 pues
        #hay un elemento que no incluye a las palabras
tokenizer = Tokenizer(num_words=vocabulary_size) #crea un tokenizador para las 14 palabras + 1 elemento

In [4]:
tokenizer.fit_on_texts(texts) #asigna las palabras con el tokenizador
print(tokenizer.index_word) #imprime el tokenizador, el cual es un diccionario con id como llave
        #y como value tiene las palabras

{1: 'is', 2: 'my', 3: 'dog', 4: 'gets', 5: 'along', 6: 'with', 7: 'cats', 8: 'that', 9: 'cat', 10: 'vicious', 11: 'happy', 12: 'when', 13: 'it', 14: 'lunch'}


In [5]:
print(tokenizer.texts_to_matrix(texts)) #obtiene una matriz a partir de las palabras, cada renglon
        #representa una oración de texts, el 1 en la columna "i" corresponde con el valor del tokenizador, en este ejemplo no
        #se toma en cuenta el orden original de las palabras, solo la presencia de estas

[[0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]]


In [6]:
print(np.round(tokenizer.texts_to_matrix(texts, mode='tfidf'), 1)) #Term frequency – Inverse document frequency
        #es una medida numérica que representa que tan importante es una palabra en un documento

[[0.  0.  0.7 0.7 0.9 0.9 0.9 0.9 0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.7 0.  0.  0.  0.  0.  0.  0.9 0.9 0.9 0.  0.  0.  0. ]
 [0.  1.2 0.7 0.7 0.  0.  0.  0.  0.  0.  0.  0.9 0.9 0.9 0.9]]


In [7]:
print(tokenizer.texts_to_sequences(texts)) #convierte el texto a una lista de arreglos, cada arreglo
        #de la lista es una oración, y los arreglos están llenos de los id's de las palabras.

[[2, 3, 4, 5, 6, 7], [8, 9, 1, 10], [2, 3, 1, 11, 12, 13, 1, 14]]
